WITH SALES_DATA AS (
    SELECT B.BOOK_ID AS BOOK_ID, SUM(B.PRICE * BS.SALES) AS TOTAL_PRICE
    FROM BOOK AS B
    JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
    WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE <= '2022-01-31'
    GROUP BY B.BOOK_ID
)
SELECT A.AUTHOR_ID AS AUTHOR_ID, A.AUTHOR_NAME AS AUTHOR_NAME, B.CATEGORY AS CATEGORY, SUM(S.TOTAL_PRICE) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN SALES_DATA S ON S.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY, A.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC;
