SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN ( -- 우유
    SELECT CP1.CART_ID FROM CART_PRODUCTS AS CP1 WHERE CP1.NAME = 'Milk'
)
AND CART_ID IN (
    SELECT CP1.CART_ID FROM CART_PRODUCTS AS CP1 WHERE CP1.NAME = 'Yogurt'
)
ORDER BY CART_ID;