-- 세단 또는 SUV인 차
-- 2022.11.01 ~ 2022.11.30까지 대여 가능
-- 30일단 대여금액이 50만원 이상, 200만원 미만
-- 결과는 대여금액 기준 내림차순 정렬. 대여 금액이 같은 경우 자동차 종류를 기준으로 오름차순 정렬, ID 기준 내림차순 정렬

# SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE IN ('세단', 'SUV');



SELECT DISTINCT CC.CAR_ID AS CAR_ID, CC.CAR_TYPE AS CAR_TYPE, CONVERT(30 * CC.DAILY_FEE * ((100-CD.DISCOUNT_RATE) / 100), SIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
JOIN CAR_RENTAL_COMPANY_CAR AS CC ON CC.CAR_ID = CH.CAR_ID
JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE IN ('세단', 'SUV')) AS CD ON CD.CAR_TYPE = CC.CAR_TYPE
WHERE CC.CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH2
    WHERE (CH2.START_DATE <= '2022-11-01' AND CH2.END_DATE >= '2022-11-30')
    OR (CH2.START_DATE >= '2022-11-01' AND CH2.START_DATE <= '2022-11-30')
    OR (CH2.END_DATE >= '2022-11-01' AND CH2.END_DATE <= '2022-11-30')
)
AND CC.CAR_TYPE IN ('세단', 'SUV')
GROUP BY CC.CAR_ID
HAVING FEE >= 500000 AND FEE <= 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;

# -- 코드를 입력하세요
# WITH CANT_RENTAL AS (
#     SELECT DISTINCT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE (END_DATE >= '2022-11-01' AND END_DATE < '2022-12-01') OR (START_DATE >= '2022-11-01' AND START_DATE < '2022-12-01') OR (START_DATE < '2022-11-01' AND END_DATE >= '2022-12-01')
    
# ),
# DISCOUNT AS (
#     SELECT CAR_TYPE, DISCOUNT_RATE 
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#     WHERE DURATION_TYPE	= '30일 이상'
# )
# SELECT C.CAR_ID, C.CAR_TYPE, 
# CONVERT((C.DAILY_FEE * 30) * (100 - D.DISCOUNT_RATE) / 100 , UNSIGNED) FEE
# FROM CAR_RENTAL_COMPANY_CAR C JOIN DISCOUNT D 
# ON C.CAR_TYPE = D.CAR_TYPE 
# WHERE C.CAR_ID NOT IN (SELECT * FROM CANT_RENTAL)
# HAVING FEE BETWEEN 500000 AND 1999999
# ORDER BY 3 DESC, 2 ASC , 1 DESC