SELECT R.FOOD_TYPE FOOD_TYPE, R.REST_ID REST_ID, R.REST_NAME REST_NAME, R.FAVORITES FAVORITES
FROM REST_INFO R,
    (SELECT FOOD_TYPE FT, MAX(FAVORITES) F FROM REST_INFO GROUP BY FOOD_TYPE) AS MT
WHERE MT.FT = R.FOOD_TYPE AND MT.F = R.FAVORITES ORDER BY FOOD_TYPE DESC;