SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

# SELECT *, DATEDIFF(END_DATE, START_DATE)FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY ORDER BY car_id;