SELECT FP.PRODUCT_ID AS PRODUCT_ID, FP.PRODUCT_NAME AS PRODUCT_NAME, SUM(FO.AMOUNT)* FP.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
JOIN FOOD_ORDER AS FO ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE FO.PRODUCE_DATE >= '2022-05-01' AND FO.PRODUCE_DATE <= '2022-05-31'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;

# SELECT PRODUCT_ID, SUM(AMOUNT)
# FROM FOOD_ORDER
# WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE <= '2022-05-31'
# GROUP BY PRODUCT_ID;

