SELECT f.PRODUCT_ID AS PRODUCT_ID, f.PRODUCT_NAME AS PRODUCT_NAME, SUM(o.AMOUNT * f.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS f
JOIN FOOD_ORDER o ON f.PRODUCT_ID = o.PRODUCT_ID
WHERE DATE_FORMAT(o.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;