SELECT A.APNT_NO AS APNT_NO, P.PT_NAME AS PT_NAME, P.PT_NO AS PT_NO, A.MCDP_CD AS MCDP_CD, D.DR_NAME AS DR_NAME, A.APNT_YMD AS APNT_YMD
FROM APPOINTMENT AS A
JOIN DOCTOR AS D ON D.DR_ID = A.MDDR_ID
JOIN PATIENT AS P ON P.PT_NO = A.PT_NO
WHERE A.APNT_CNCL_YMD IS NULL
AND A.MCDP_CD = 'CS'
AND DATE(APNT_YMD) = '2022-04-13'
ORDER BY A.APNT_YMD;