WITH RECURSIVE CTE AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 
    FROM CTE
    WHERE HOUR < 23
),
CNT AS (
    SELECT HOUR(ANIMAL_OUTS.DATETIME) AS H, COUNT(*) AS C
    FROM ANIMAL_OUTS
    GROUP BY H
)
SELECT CTE.HOUR AS HOUR, IFNULL(CNT.C, 0) AS COUNT
FROM CNT RIGHT JOIN CTE ON CNT.H = CTE.HOUR
GROUP BY HOUR
ORDER BY HOUR;