WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM CTE
    WHERE HOUR < 23
),
COUNT_TABLE AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS AS O
    GROUP BY HOUR(DATETIME)
)
SELECT CTE.HOUR AS HOUR, IFNULL(COUNT_TABLE.COUNT, 0) AS COUNT
FROM CTE
LEFT JOIN COUNT_TABLE ON COUNT_TABLE.HOUR = CTE.HOUR
ORDER BY HOUR;