WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM CTE
    WHERE HOUR < 23
),
ANIMAL_COUNT AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
)
SELECT CTE.HOUR AS HOUR, IFNULL(ANIMAL_COUNT.COUNT, 0) AS COUNT
FROM ANIMAL_COUNT
RIGHT JOIN CTE ON CTE.HOUR = ANIMAL_COUNT.HOUR
GROUP BY HOUR
ORDER BY HOUR;