-- 등급 구하기


WITH GRADE AS (
    SELECT EMP_NO, AVG(SCORE) AS AVERAGE,
(CASE
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C'
 END) AS GRADE
FROM HR_GRADE
GROUP BY EMP_NO
)
SELECT E.EMP_NO EMP_NO, E.EMP_NAME EMP_NAME, G.GRADE GRADE,
CONVERT(CASE WHEN G.GRADE = 'S' THEN E.SAL * 0.2
WHEN G.GRADE = 'A' THEN E.SAL * 0.15
WHEN G.GRADE = 'B' THEN E.SAL * 0.1
ELSE 0 END, SIGNED) AS BONUS
FROM HR_EMPLOYEES AS E
JOIN GRADE G ON G.EMP_NO = E.EMP_NO
ORDER BY EMP_NO;