SELECT MONTH(h.START_DATE) AS MONTH, h.CAR_ID AS CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
WHERE CAR_ID IN (
SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h2 WHERE h2.START_DATE >= '2022-08-01' AND h2.START_DATE <= '2022-10-31' GROUP BY CAR_ID HAVING COUNT(CAR_ID) >= 5
)
AND h.START_DATE >= '2022-08-01' AND h.START_DATE <= '2022-10-31'
GROUP BY MONTH, CAR_ID
HAVING RECORDS >= 1
ORDER BY MONTH, CAR_ID DESC;