SELECT fi.ID AS ID, fn.FISH_NAME AS FISH_NAME, fi.LENGTH AS LENGTH
FROM FISH_INFO AS fi
JOIN FISH_NAME_INFO AS fn ON fi.FISH_TYPE = fn.FISH_TYPE
WHERE fi.LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO WHERE fi.FISH_TYPE = FISH_INFO.FISH_TYPE)
ORDER BY ID;