# -- 코드를 입력하세요
SELECT FOOD_PRODUCT.CATEGORY AS CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
INNER JOIN (
    SELECT FP.CATEGORY AS CATEGORY, MAX(FP.PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT AS FP
    WHERE FP.PRODUCT_ID = PRODUCT_ID
    GROUP BY FP.CATEGORY
) AS MPT ON MPT.CATEGORY = FOOD_PRODUCT.CATEGORY
WHERE MPT.MAX_PRICE = FOOD_PRODUCT.PRICE AND MPT.CATEGORY = FOOD_PRODUCT.CATEGORY
AND FOOD_PRODUCT.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;
