SELECT FP.CATEGORY AS CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME AS PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN (SELECT F.CATEGORY AS CATEGORY, MAX(F.PRICE) AS MAX_PRICE FROM FOOD_PRODUCT AS F GROUP BY F.CATEGORY) AS MP
ON MP.CATEGORY = FP.CATEGORY
WHERE MP.MAX_PRICE = FP.PRICE
AND FP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;